OneGov/Controllers/CbnFormQController.cs
using System;
using System.Data.Entity;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CBNFormQ.Models;
using Microsoft.AspNet.Identity;
using PayStack.Net;
using Rotativa;
using Rotativa.Options;

namespace CBNFormQ.Controllers
{
    public class CbnFormQController : BaseController
    {
        private static PayStackApi _api;
        private readonly OneGovDbContext db = new OneGovDbContext();

        // GET: CbnFormQ
        public ActionResult Index()
        {
            return View(db.CbnFormQViewModels.ToList());
        }

        [HttpPost]
        public JsonResult Paystack(object request, string Bvn)
        {
            _api = new PayStackApi("sk_live_27a5ba903be8e7f5a862eaf39d26b916a28eac0d");

            //request = _api.ResolveCardBin("539941");

            request = _api.ResolveBvn(Bvn);

            (request as IPreparable)?.Prepare();

            //var bin = JsonConvert.SerializeObject(request, Formatting.Indented, PayStackApi.SerializerSettings);

            return Json(request, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ListBanks(object request)
        {
            _api = new PayStackApi("sk_test_760c409e1e8e60e037b6e6d7b68ab5f51d3c2f90");

            request = _api.SubAccounts.GetBanks();

            (request as IPreparable)?.Prepare();

            //var bin = JsonConvert.SerializeObject(request, Formatting.Indented, PayStackApi.SerializerSettings);

            return Json(request, JsonRequestBehavior.AllowGet);
        }

        // GET: CbnFormQ/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            if (cbnFormQViewModel == null)
                return HttpNotFound();
            return View(cbnFormQViewModel);
        }


        // GET: CbnFormQ/Generated/5
        public ActionResult Generated(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            if (cbnFormQViewModel == null)
                return HttpNotFound();
            return View(cbnFormQViewModel);
        }

        [AllowAnonymous]
        public ActionResult GeneratedPdf(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            if (cbnFormQViewModel == null)
                return HttpNotFound();
            return new ViewAsPdf("Generated", cbnFormQViewModel)
            {
                //FileName = cbnFormQViewModel.FullName + "CBN FormQ" + ".pdf",
                PageSize = Size.A4,
                PageOrientation = Orientation.Portrait
            };
        }

        [AllowAnonymous]
        public ActionResult PaymentConfirmation()
        {
            return View();
        }

        // GET: CbnFormQ/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CbnFormQ/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CbnFormQViewModel cbnFormQViewModel, object request, string Bvn, string BankName,
            string TransactionRef)
        {
            if (ModelState.IsValid)
            {
                cbnFormQViewModel.Email = User.Identity.GetUserName();

                cbnFormQViewModel.SubmissionDate = DateTime.Now.ToLongDateString();

                _api = new PayStackApi("sk_test_760c409e1e8e60e037b6e6d7b68ab5f51d3c2f90");

                var verifyResponse = _api.Transactions.Verify(TransactionRef); // auto or supplied when initializing;
                Debug.WriteLine(TransactionRef);
                db.CbnFormQViewModels.Add(cbnFormQViewModel);
                db.SaveChanges();
                RedirectToAction("Dashboard", "Home");
            }

            return View(cbnFormQViewModel);
        }

        // GET: CbnFormQ/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            if (cbnFormQViewModel == null)
                return HttpNotFound();
            return View(cbnFormQViewModel);
        }

        // POST: CbnFormQ/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include =
                "Id,Bvn,Mobile,Email,AnnualTurnover,NumberOfEmployees,BankName,AccountNumber,ItemOfImport,BeneficiaryName,BeneficiaryBankName,BeneficiaryBankAdress,Iban,SwiftCode,Amount,AmountInWords,Purpose")]
            CbnFormQViewModel cbnFormQViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cbnFormQViewModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cbnFormQViewModel);
        }


        // GET: CbnFormQ/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            if (cbnFormQViewModel == null)
                return HttpNotFound();
            return View(cbnFormQViewModel);
        }

        // POST: CbnFormQ/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var cbnFormQViewModel = db.CbnFormQViewModels.Find(id);
            db.CbnFormQViewModels.Remove(cbnFormQViewModel);
            db.SaveChanges();
            return RedirectToAction("Dashboard", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OneGov/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CBNFormQ.Models;

namespace CBNFormQ.Controllers
{
    public class HomeController : Controller
    {
        private OneGovDbContext db = new OneGovDbContext();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Services()
        {
            return View();
        }

        public ActionResult Dashboard()
        {

            return View(db.CbnFormQViewModels.ToList());
        }
    }
}

OneGov/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OneGov/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OneGov/Views/Home/Dashboard.cshtml
@model IEnumerable<CBNFormQ.Models.CbnFormQViewModel>

@{
    ViewBag.Title = "Dashboard";
    Layout = null;
}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - OneGov Nigeria</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body style="background: linear-gradient(to bottom,#3aa6df 0,#f9f9f9 580px,#f9f9f9 100%);">
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("OneGov Nigeria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Services", "Services", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    <div class="col-sm-3 col-md-3">
                        <form class="navbar-form" role="search">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Search" name="q">
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">

            <div class="main">
                <div class="row" style="margin-top: 20px;">
                    <div class="col-md-8">
                        <p style="font-size: 1.25rem; margin: 0;">ONEGOV NIGERIA</p>
                        <h1 style="margin: 0; color: #01beff;">MY APPLICATIONS</h1>
                    </div>
                    <div class="col-md-4 right">
                        <a href="@Url.Action("Create", "CbnFormQ")" class="btn btn-danger pull-right" style="margin-top: 23px;">
                            New Application
                            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>

                <hr />


                <div class="container">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            <ul class="listrap">
                                <li>
                                    <div class="listrap-toggle">
                                        <span></span>
                                        <img src="http://lorempixel.com/60/60/people/?v=1" class="img-circle" />
                                    </div>
                                    <strong class="col-md-offset-2 text-center">@item.FullName</strong>
                                    <strong class="col-md-offset-2 text-center">CBN Form Q</strong>
                                    <span class="pull-right" style="margin-top: 10px;">
                                        @Html.ActionLink("View | ", "GeneratedPdf", "CbnFormQ", new { id = item.Id }, new { style = "vertical-align: -webkit-baseline-middle;", target = "_blank" })
                                        @Html.ActionLink("Delete", "Delete", "CbnFormQ", new { id = item.Id }, new { style = "vertical-align: -webkit-baseline-middle;" })
                                    </span>
                                </li>
                            </ul>
                            <hr style="margin: 0;" />

                        }
                    </div>
                </div>
            </div>

            <script>
                jQuery.fn.extend({
                    listrap: function () {
                        var listrap = this;
                        listrap.getSelection = function () {
                            var selection = new Array();
                            listrap.children("li.active").each(function (ix, el) {
                                selection.push($(el)[0]);
                            });
                            return selection;
                        }
                        var toggle = "li .listrap-toggle ";
                        var selectionChanged = function () {
                            $(this).parent().parent().toggleClass("active");
                            listrap.trigger("selection-changed", [listrap.getSelection()]);
                        }
                        $(listrap).find(toggle + "img").on("click", selectionChanged);
                        $(listrap).find(toggle + "span").on("click", selectionChanged);
                        return listrap;
                    }
                });
                $(document).ready(function () {
                    $(".listrap").listrap().on("selection-changed", function (event, selection) {
                        console.log(selection);
                    });
                });
            </script>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
    </body>
</html>

OneGov/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_CarouselPartial")

<h3>Categories</h3>

<div class="row">
    <div class="col-xs-6 col-md-3">
        <a href="@Url.Action("Index", "CbnFormQ")" class="thumbnail">
            <img src="~/Content/Images/thumb_01.jpg" alt="...">
            <div class="caption">
                <h4>CBN Form Q</h4>
                <p>Fill and process your CBN Form queue with no hassle.</p>
            </div>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
            <img src="~/Content/Images/thumb_02.jpg" alt="...">
            <div class="caption">
                <h4>Drivers License</h4>
                <p>Get your license in days so that you can drive without fear.</p>
            </div>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
            <img src="~/Content/Images/thumb_03.jpg" alt="...">
            <div class="caption">
                <h4>Corporate Affairs</h4>
                <p>Process your company registration details in seconds :-)</p>
            </div>
        </a>
    </div>
    <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
            <img src="~/Content/Images/thumb_04.jpg" alt="...">
            <div class="caption">
                <h4>National ID Card</h4>
                <p>Get a card to show that you are a Nigerian.</p>
            </div>
        </a>
    </div>
 
</div>




@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@

OneGov/Views/Home/Services.cshtml
@{
    ViewBag.Title = "Services";
}

<h2>Services</h2>